name: Slack Release BOT
author: homeday-de
description: Slack Release BOT used by Homeday engineering
inputs:
  webhook_url:
    required: true
    description: Slack webhook URL
  title:
    required: true
    description: Message title
  body:
    required: false
    description: Message body (markdown allowed but needs to be Slackified first)
  context:
    required: true
    description: Which project is being released?
runs:
  using: 'composite'
  steps:
    - name: Announce on Slack 📢
      shell: bash
      run: |
        header='{
          "type": "header",
          "text": {
          "type": "plain_text",
          "text": "${{ inputs.title }}"
          }
        },'
        divider='{
          "type": "divider"
        },'
        # Slack markdown doesn't accept empty `text`
        if [ ! -z '${{ inputs.body }}' ]
        then
          body='{
            "type": "section",
            "text": {
            "type": "mrkdwn",
            "text": "${{ inputs.body }}"
            }
          },'
        fi
        context='{
          "type": "context",
          "elements": [
          {
            "type": "plain_text",
            "text": "${{ inputs.context }}"
          }
          ]
        }'
        blocks='"blocks": [
          '$header'
          '$divider'
          '$body'
          '$context'
        ]'
        data='{'$blocks'}'
        
        curl ${{ inputs.webhook_url }} \
          --request POST \
          --header 'Content-type: application/json' \
          --data $data
